version: '3.3'

services:

  copa:
    image: kaiquesmend/copa
    depends_on:
      - db_copa
    restart: always
    ports:
      - "80:8080"
    environment:
      - DATABASE_PASSWORD=Copa01@!
      - DATABASE_URL=jdbc:postgresql://db_copa:5432/copa
      - DATABASE_USER=copa_user

  db_copa:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=copa_user
      - POSTGRES_PASSWORD=Copa01@!
      - POSTGRES_DB=copa
